application:
  subdomain: jetbrains-server
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://jetbra-server:10768/

services:
  jetbra-server:
    container_name: jetbra-server
    image: docker.1ms.run/czyt/jetbra:v1.1.3
    environment:
      - PORT=10768
