lzc-sdk-version: "0.1"
name: Jetbrains Server
min_os_version: 1.3.8
package: czyt.app.jetbrains-server
version: 0.2.9
description: jetbrains License Server
homepage: https://czyt.tech
author: czyt
application:
  subdomain: jetbrains-server
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://jetbra-server:8080

services:
  jetbra-server:
    container_name: jetbra-server
    image: docker.hlmirror.com/czyt/jetbra-server:v0.2.9
    environment:
      - BIND_ALL={{.U.bindall}}
      - AUTH_USER={{.U.authuser}}
      - AUTH_PASS={{.U.authpass}}
